export const story = {
  start: "n0",
  nodes: {
    n0: {
      largeTitle: "Again.",
      body: "By Galen Reich. Scroll to explore.",
      down: "n2",
      image: "images/again.jpg",
      imageAlt: "A skull on a book by a candle.",
    },
    n1: {
      largeTitle: "Again.",
      down: "n2",
      image: "images/again.jpg",
      imageAlt: "A skull on a book by a candle.",
    },
    n2: {
      title: "I have been read before.",
      down: "n3",
      up: "p1",
    },
    n3: {
      title: "Beneath a flickering lamp",
      body: "and a vaulted ceiling.",
      image: "images/vaulted.jpg",
      imageAlt: "Gothic architecture.",
      down: "n4",
      up: "n2",
    },
    n4: {
      title: "I have been read before.",
      down: "n5",
      up: "r2",
    },
    n5: {
      title: "In a stolen second",
      body: "before a wake.",
      image: "images/fiddle.jpg",
      imageAlt: "A fiddle.",
      down: "n6",
      up: "n4",
    },
    n6: {
      title: "I have been read before.",
      down: "n7",
      up: "r2",
    },
    n7: {
      title: "In a moment of quiet",
      body: "by hardened eyes.",
      image: "images/eye.jpg",
      imageAlt: "An arched eye.",
      down: "n8",
      up: "p0",
    },
    n8: {
      title: "But how am I remembered?",
      up: "p1",
      image: "images/ouroboros.jpg",
      imageAlt: "An hourglass surrounded by a snake eating its own tail.",
    },
    p0: {
      title: "I have been read before.",
      up: "p3",
      down: "r2",
    },
    p1: {
      title: "By hardened eyes",
      body: "and a vaulted ceiling.",
      image: "images/vaulted.jpg",
      imageAlt: "Gothic architecture.",
      up: "p2",
      down: "a0",
    },
    p2: {
      title: "I have been read before.",
      up: "n5",
      down: "r2",
    },
    p3: {
      title: "In a lonely castle",
      body: "by a roaring fire.",
      up: "n2",
      down: "q1",
      image: "images/castle.jpg",
      imageAlt: "A turreted castle.",
    },
    q1: {
      title: "I have been read before.",
      up: "q1",
      down: "q2",
    },
    q2: {
      title: "But who are you",
      body: "that reads me?",
      up: "q2",
      down: "q3",
      image: "images/abstract.jpg",
      imageAlt: "An abstract geometry.",
    },
    q3: {
      title: "I see your eyes",
      body: "dance across the page.",
      down: "q4",
      up: "j1",
    },
    q4: {
      title: "I hear your breath",
      body: "but you are not the first.",
      down: "q5",
      up: "j1",
    },
    q5: {
      title: "I have been read before.",
      up: "q2",
      down: "p1",
    },
    r1: {
      title: "I have been read before.",
      up: "q2",
      down: "q2",
    },
    r2: {
      title: "As stars explode on distant shores",
      body: "and wings beat in the night.",
      image: "images/star_explodes.jpg",
      imageAlt: "An exploding supernova.",
      up: "r1",
      down: "r3",
    },
    r3: {
      title: "I have been read before.",
      up: "r2",
      down: "r4",
    },
    r4: {
      title: "On the deathbed of a queen",
      body: "while her people mourn.",
      image: "images/skull_queen.jpg",
      imageAlt: "A skull with a crown.",
      up: "r3",
      down: "r5",
    },
    r5: {
      title: "I have been lost again.",
      image: "images/chronograph.jpg",
      imageAlt: "A watch with exposed gears.",
      up: "n1",
      down: "n1",
    },
    a0: {
      title: "I have been heard before.",
      down: "a1",
      up: "a4",
    },
    a1: {
      title: "A plotter screams.",
      body: "A musician cries.",
      image: "images/web.jpg",
      imageAlt: "A spider encompasses two embracing figures.",
      down: "a2",
      up: "a5",
    },
    a2: {
      title: "A flower wilts.",
      body: "A loved one dies.",
      image: "images/wilt.jpg",
      imageAlt: "A wilting flower.",
      up: "a1",
      down: "a3",
    },
    a3: {
      title: "A chanted psalm.",
      body: "A forgotten rhyme.",
      down: "a4",
      up: "a2",
      image: "images/egg.jpg",
      imageAlt: "A cracked egg with a face.",
    },
    a4: {
      title: "A hymnal book.",
      body: "A perfect crime.",
      up: "a3",
      down: "a5",
      image: "images/death_hourglass.jpg",
      imageAlt: "Death and an hourglass.",
    },
    a5: {
      title: "I shall be heard again.",
      image: "images/chronograph.jpg",
      imageAlt: "A watch with exposed gears.",
      down: "n1",
      up: "n1",
    },

    j1: {
      title: "I have been here before.",
      up: "j2",
      down: "p3",
    },
    j2: {
      title: "An outstretched hand",
      body: "draws me down.",
      up: "j3",
      down: "r1",
    },
    j3: {
      title: "I have been here before.",
      up: "j4",
      down: "r2",
    },
    j4: {
      title: "Sharing my words",
      body: "again and again.",
      up: "j5",
      down: "j5",
    },
    j5: {
      title: "I shall be read once more.",
      image: "images/read.jpg",
      imageAlt: "A person reading a book.",
    },
  },
};
